apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roadmap-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # CORS configuration
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledgelink.up.railway.app, https://your-frontend-domain.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    # WebSocket support
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-set-headers: |
      Upgrade $http_upgrade;
      Connection "Upgrade";
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - backend.aswanth.online
    secretName: knowledgelink-tls
  rules:
  - host: backend.aswanth.online
    http:
      paths:
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 5000
      - path: /roadmap(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: roadmap-service
            port:
              number: 5001
      - path: /profile(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: profile-service
            port:
              number: 5002
      - path: /post(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: post-service
            port:
              number: 5003
      - path: /notification(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 5004
      - path: /chat(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-service
            port:
              number: 5005
      - path: /recommendation(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 5006
      - path: /(chat/socket\.io)(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-service
            port:
              number: 5005
  ingressClassName: nginx