name: Build and Push Docker Images

on:
  push:
    branches:
      - deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, roadmap, profile, post, notification, chat, recommendation]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./backend/${{ matrix.service }}-service
        push: true
        tags: aswantht/roadmap-${{ matrix.service }}-service:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
